// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ3F1i-2DjqX9A7NoTA30Vcz099Q85d10',
    appId: '1:285609775559:web:40afd01b121f659511c9e2',
    messagingSenderId: '285609775559',
    projectId: 'vibes-app-81000',
    authDomain: 'vibes-app-81000.firebaseapp.com',
    storageBucket: 'vibes-app-81000.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5sV7P_DcI_zY9a582jEEOKRHTWNA_87U',
    appId: '1:285609775559:android:f154582c4c34907e11c9e2',
    messagingSenderId: '285609775559',
    projectId: 'vibes-app-81000',
    storageBucket: 'vibes-app-81000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP_Mx11UayqKtijgMuFOTig3586AqHqQY',
    appId: '1:285609775559:ios:68fb4ca27064a21911c9e2',
    messagingSenderId: '285609775559',
    projectId: 'vibes-app-81000',
    storageBucket: 'vibes-app-81000.appspot.com',
    iosBundleId: 'com.example.vibesApp',
  );
}
